### ISSUE TITLE
EMERGENCY 

### ISSUE THREAD

**Issue by ShengWang11** [sujitpal/fttl-with-keras#1]
@sujitpal 
Hello sir. I am a fresher.And thanks for your sharing, but I'm meeting some troubles.
I can not find the make-sample.py refered in the dataset so that the dataset making failed. Wish you can send it to me or offer some solutions. And I'll be much appreciated with that.

**Comment by sujitpal** [comment]
Sorry, I must have deleted it. I rebuilt a make-sample.py and put it back into the src directory.
